# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ff2f7e834d7d9cb8c32bfd9d3e4cda7fcfb5f34a75c047fde28c876c8c810a9192adca6a5e82b5060db17648d1f300bbbfa3fe95fff598236586176b9e2763b

test:
  secret_key_base: f004beeeb68f393234f93c2e0b0dbc6f8513d07631f70f1f438b408d98b3bf8e7356033e6755acea85632ef2abb05a1ba36b6095856bb78b3146514693e95fa3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
